Repository JuliaDiff/ChainRulesCore.jl, pull requests merged in 2020-07, with the labels that each got.

#185 Differential addition for empty tuples fix in composite.jl
  Project.toml
  src/differentials/composite.jl
  test/differentials/composite.jl
Labels: bug

#191 Add docs page on deriving array rules
  docs/make.jl
  docs/src/arrays.md
Labels: Complex Differentiation, documentation

#183 Dictionary differentials
  Project.toml
  docs/Manifest.toml
  src/differential_arithmetic.jl
  src/differentials/composite.jl
  test/differentials/composite.jl
Labels: enhancement
