Repository JuliaDiff/ChainRulesCore.jl, pull requests merged in 2021-08, with the labels that each got.

#424 Fix two bugs in `ProjectTo`
  Project.toml
  src/projection.jl
  test/projection.jl
Labels: ProjectTo

#428 FAQ: What types does my pullback need to accept?
  docs/src/FAQ.md
  docs/src/writing_good_rules.md
Labels: documentation

#427 Fix #426 -- gradient of Ref is a Tangent
  Project.toml
  src/differentials/abstract_zero.jl
  src/projection.jl
  test/differentials/abstract_zero.jl
  test/projection.jl
Labels: Structural Tangent, ProjectTo
